"""add plugins table

Revision ID: 0fad6f848916
Revises: a1b2c3d4e5f6
Create Date: 2026-03-28 16:18:23.225591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fad6f848916'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('plugin_type', sa.String(), nullable=False),
    sa.Column('install_path', sa.String(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('ui_slots', sa.Text(), nullable=False),
    sa.Column('hooks', sa.Text(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.Column('settings_values', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('permissions_granted', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugins')
    # ### end Alembic commands ###
