"""initial schema

Revision ID: d2be98a7a8b3
Revises: 
Create Date: 2026-03-25 22:54:10.994286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2be98a7a8b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('os', sa.String(length=256), nullable=True),
    sa.Column('os_accuracy', sa.Integer(), nullable=True),
    sa.Column('mac', sa.String(length=32), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ip', name='uq_host_project_ip')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_project_id'), ['project_id'], unique=False)

    op.create_table('targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_project_id'), ['project_id'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_target_id'), ['target_id'], unique=False)

    op.create_table('ports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=256), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'number', 'protocol', name='uq_port_host_proto')
    )
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ports_host_id'), ['host_id'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('source_scan', sa.String(), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('hash', sa.String(length=512), nullable=True),
    sa.Column('hash_type', sa.String(length=32), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_scan'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_project_id'), ['project_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('cve', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('tool_source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)

    op.create_table('finding_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_evidence_finding_id'), ['finding_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_project_id'))

    op.drop_table('notes')
    with op.batch_alter_table('finding_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_evidence_finding_id'))

    op.drop_table('finding_evidence')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_findings_project_id'))

    op.drop_table('findings')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_project_id'))

    op.drop_table('credentials')
    op.drop_table('scan_results')
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ports_host_id'))

    op.drop_table('ports')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_target_id'))
        batch_op.drop_index(batch_op.f('ix_scans_project_id'))

    op.drop_table('scans')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_project_id'))

    op.drop_table('targets')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_project_id'))

    op.drop_table('hosts')
    # ### end Alembic commands ###
